import Link from 'next/link';
import type { Metadata } from 'next';
import { breadcrumbJsonLd, jsonLdScript } from '@/lib/structured-data';
import { LEGAL_ENTITY, PRIVACY_EMAIL } from '@/lib/site-config';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'The terms governing use of MARKUP — accounts, AI-generated practice content, grading, acceptable use, and disclaimers for the Singapore O-Level Humanities platform.',
  alternates: { canonical: '/terms' },
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#07090e] text-slate-100 font-sans selection:bg-indigo-500/30">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: jsonLdScript(
            breadcrumbJsonLd([
              { name: 'Home', href: '/' },
              { name: 'Terms of Service', href: '/terms' },
            ])
          ),
        }}
      />
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16 space-y-8">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <Link
            href="/"
            className="text-[11px] text-slate-500 hover:text-slate-300 transition font-bold whitespace-nowrap"
          >
            ← Back
          </Link>
          <h1 className="text-2xl font-black text-indigo-500 tracking-wider">MARKUP</h1>
        </div>

        <h2 className="text-3xl font-black text-white tracking-tight">Terms of Service</h2>
        <p className="text-xs text-slate-500 font-mono">Last updated: September 2026</p>

        {/* Affiliation disclaimer — kept prominent, above the numbered sections */}
        <div className="bg-amber-950/20 border border-amber-900/40 rounded-2xl p-4">
          <p className="text-[10px] font-black text-amber-300 uppercase tracking-widest">
            Not affiliated with SEAB, MOE or Cambridge
          </p>
          <p className="text-xs text-slate-400 mt-1.5 leading-relaxed">
            MARKUP is an independent study tool operated by {LEGAL_ENTITY}. We are not
            affiliated with, endorsed by, or connected to the Singapore Examinations and
            Assessment Board (SEAB), the Ministry of Education (MOE), Cambridge Assessment, or
            any school. Names such as &ldquo;GCE O-Level&rdquo; and &ldquo;SEAB&rdquo; belong to
            their respective owners and are used only to describe the syllabus you are
            practising. AI grades are practice feedback — not official results — and we do not
            promise any particular grade, mark, or examination outcome.
          </p>
        </div>

        <div className="space-y-6 text-sm text-slate-400 leading-relaxed">
          <section className="space-y-3">
            <h3 className="text-base font-bold text-white">1. Acceptance of Terms</h3>
            <p>
              By accessing or using MARKUP (&ldquo;the Service&rdquo;), you agree to be bound by these
              Terms of Service. If you do not agree, please do not use the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-base font-bold text-white">2. Description of Service</h3>
            <p>
              MARKUP is an AI-powered humanities practice platform for Singapore GCE O-Level
              Social Studies, Elective History, and Pure History students. The Service provides
              AI-generated practice papers, automated grading modelled on the SEAB LORMS
              rubric, progress tracking through gamification (XP, levels, achievements), and
              study group features. Practice papers are generated by AI and are not real
              examination papers.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-base font-bold text-white">3. Beta Period</h3>
            <p>
              The Service is currently in beta. All features are provided free of charge during
              this period. We reserve the right to introduce pricing tiers after the beta period
              ends. Beta users may be offered preferential pricing as described on our pricing
              page.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-base font-bold text-white">4. User Accounts</h3>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>You must be a secondary school student or educator to use the Service</li>
              <li>
                If you are under 13, a parent or guardian must set up the account and accept
                these terms on your behalf. If you are 13 to 17, you may accept them yourself —
                but if any part is unclear, please ask a parent, guardian, or teacher before you
                sign up. See our Privacy Policy for how we handle children&apos;s data
              </li>
              <li>Any paid plan must be purchased by someone aged 18 or over</li>
              <li>You are responsible for maintaining the confidentiality of your login credentials</li>
              <li>You must provide accurate email information for account-related communications</li>
              <li>One person per account — sharing login credentials is not permitted</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h3 className="text-base font-bold text-white">5. Acceptable Use</h3>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to bypass our AI grading system or manipulate XP/achievements</li>
              <li>Upload malicious content or attempt to compromise the Service</li>
              <li>Use automated scripts to generate excessive API calls</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h3 className="text-base font-bold text-white">6. AI Grading Disclaimer</h3>
            <p>
              AI-generated grades are provided as practice feedback and should not be considered
              equivalent to official SEAB marking. Our grading is modelled on the published
              LORMS approach, but it is our own implementation and is not reviewed, approved, or
              endorsed by SEAB or any examiner. The AI may occasionally produce incorrect or
              inconsistent feedback. Always consult your teacher for official assessment of your
              work.
            </p>
            <p>
              We make no promise about the grade, mark, or outcome you will achieve in any
              examination. How much you improve depends on how you use the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-base font-bold text-white">7. Intellectual Property</h3>
            <p>
              The Service, including its code, design, and AI models, is owned by Markup
              Analytics. Generated practice papers and grading feedback are provided for your
              personal educational use. You retain ownership of your essay submissions.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-base font-bold text-white">8. Limitation of Liability</h3>
            <p>
              The Service is provided &ldquo;as is&rdquo; without warranty. We are not liable for any
              damages arising from your use of the Service, including but not limited to
              academic performance or exam results.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-base font-bold text-white">9. Changes to Terms</h3>
            <p>
              We may update these terms at any time. Users will be notified of material changes
              via email. Continued use of the Service after changes constitutes acceptance of
              the new terms.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-base font-bold text-white">10. Contact</h3>
            <p>
              For questions about these terms, or about how we handle personal data, contact{' '}
              {LEGAL_ENTITY} at{' '}
              <a
                href={`mailto:${PRIVACY_EMAIL}`}
                className="text-indigo-400 hover:text-indigo-300 underline underline-offset-4"
              >
                {PRIVACY_EMAIL}
              </a>
              . You can also submit feedback from the dashboard.
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="pt-8 border-t border-slate-900 text-center">
          <Link href="/" className="text-indigo-400 hover:text-indigo-300 text-xs font-bold underline underline-offset-4 transition">
            ← Back to MARKUP
          </Link>
        </div>
      </div>
    </div>
  );
}
